<a href="https://colab.research.google.com/github/MorrowG2/Kaggle_ML_YouTube/blob/main/Rainfall_in_Australia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!ls

drive  sample_data

In [ ]:
%cd '/content/drive/My Drive/Kaggle/Did it Rain?'
!ls

/content/drive/My Drive/Kaggle/Did it Rain?
 archive.zip  'Rainfall in Australia?.ipynb'   weatherAUS.csv

In [ ]:
!unzip 'archive.zip'
!ls

Archive:  archive.zip
  inflating: weatherAUS.csv
 archive.zip  'Rainfall in Australia?.ipynb'   weatherAUS.csv

In [ ]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Kaggle/Did it Rain?/weatherAUS.csv')
df.head(1)

         Date Location  MinTemp  ...  Temp3pm  RainToday  RainTomorrow
0  2008-12-01   Albury     13.4  ...     21.8         No            No

[1 rows x 23 columns]

In [ ]:
df.columns

Index(['Date', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation',
       'Sunshine', 'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RainTomorrow'],
      dtype='object')

In [ ]:
df.dtypes

Date              object
Location          object
MinTemp          float64
MaxTemp          float64
Rainfall         float64
Evaporation      float64
Sunshine         float64
WindGustDir       object
WindGustSpeed    float64
WindDir9am        object
WindDir3pm        object
WindSpeed9am     float64
WindSpeed3pm     float64
Humidity9am      float64
Humidity3pm      float64
Pressure9am      float64
Pressure3pm      float64
Cloud9am         float64
Cloud3pm         float64
Temp9am          float64
Temp3pm          float64
RainToday         object
RainTomorrow      object
dtype: object

In [ ]:
df.RainTomorrow = df.RainTomorrow.apply(lambda x: type(x)).value_counts()

In [ ]:
df.RainTomorrow = pd.to_numeric(df.RainTomorrow, errors='coerce')

In [ ]:
df.RainTomorrow.isna().sum()

145460

In [ ]:
len(df)

145460

In [ ]:
df.isna().sum()

Date                 0
Location             0
MinTemp           1485
MaxTemp           1261
Rainfall          3261
Evaporation      62790
Sunshine         69835
WindGustDir      10326
WindGustSpeed    10263
WindDir9am       10566
WindDir3pm        4228
WindSpeed9am      1767
WindSpeed3pm      3062
Humidity9am       2654
Humidity3pm       4507
Pressure9am      15065
Pressure3pm      15028
Cloud9am         55888
Cloud3pm         59358
Temp9am           1767
Temp3pm           3609
RainToday         3261
RainTomorrow      3267
dtype: int64

In [ ]:
df.dropna(inplace=True)
df.isna().sum()

Date             0
Location         0
MinTemp          0
MaxTemp          0
Rainfall         0
Evaporation      0
Sunshine         0
WindGustDir      0
WindGustSpeed    0
WindDir9am       0
WindDir3pm       0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Cloud9am         0
Cloud3pm         0
Temp9am          0
Temp3pm          0
RainToday        0
RainTomorrow     0
dtype: int64

In [ ]:
len(df)

56420

In [ ]:
len(df.WindGustDir.unique()) == df.WindGustDir.nunique()

True

In [ ]:
df.WindGustDir.unique()

array(['SSW', 'S', 'NNE', 'WNW', 'N', 'SE', 'ENE', 'NE', 'E', 'SW', 'W',
       'WSW', 'NNW', 'ESE', 'SSE', 'NW'], dtype=object)

In [ ]:
df.head()

         Date Location  MinTemp  ...  Temp3pm  RainToday  RainTomorrow
0  2008-12-01   Albury     13.4  ...     21.8         No            No
1  2008-12-02   Albury      7.4  ...     24.3         No            No
2  2008-12-03   Albury     12.9  ...     23.2         No            No
3  2008-12-04   Albury      9.2  ...     26.5         No            No
4  2008-12-05   Albury     17.5  ...     29.7         No            No

[5 rows x 23 columns]

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.head()

            Date Location  MinTemp  ...  Temp3pm  RainToday  RainTomorrow
6049  2009-01-01    Cobar     17.9  ...     33.4         No            No
6050  2009-01-02    Cobar     18.4  ...     27.0         No            No
6052  2009-01-04    Cobar     19.4  ...     34.9         No            No
6053  2009-01-05    Cobar     21.9  ...     35.6         No            No
6054  2009-01-06    Cobar     24.2  ...     37.6         No            No

[5 rows x 23 columns]

In [ ]:
df.Location.unique()

array(['Cobar', 'CoffsHarbour', 'Moree', 'NorfolkIsland', 'Sydney',
       'SydneyAirport', 'WaggaWagga', 'Williamtown', 'Canberra', 'Sale',
       'MelbourneAirport', 'Melbourne', 'Mildura', 'Portland', 'Watsonia',
       'Brisbane', 'Cairns', 'Townsville', 'MountGambier', 'Nuriootpa',
       'Woomera', 'PerthAirport', 'Perth', 'Hobart', 'AliceSprings',
       'Darwin'], dtype=object)

In [ ]:
df.groupby('Location').mean('MinTemp')

                    MinTemp    MaxTemp  ...    Temp9am    Temp3pm
Location                                ...
AliceSprings      13.878093  29.724921  ...  22.043140  28.457175
Brisbane          16.365628  26.436810  ...  21.815137  24.746834
Cairns            21.129296  29.551596  ...  25.790139  27.872013
Canberra           7.727829  20.363822  ...  12.839239  18.917254
Cobar             13.828090  26.225281  ...  18.523783  24.873034
CoffsHarbour      14.485000  23.766304  ...  20.072174  22.193478
Darwin            23.166492  32.559536  ...  27.170967  31.110320
Hobart             8.957091  17.783961  ...  12.362249  16.096287
Melbourne         11.672445  20.590253  ...  14.501370  19.087777
MelbourneAirport   9.958313  20.494537  ...  14.123899  18.956606
Mildura           10.914225  24.957440  ...  15.702120  23.531187
Moree             12.876738  26.937376  ...  18.882959  25.640878
MountGambier       8.953996  20.059026  ...  13.969168  18.396673
NorfolkIsland     16.849432  21.767857  ...  19.697768  20.431940
Nuriootpa          9.707570  22.026444  ...  15.136056  20.601295
Perth             13.066215  25.188066  ...  18.750975  23.589223
PerthAirport      12.681050  25.607793  ...  18.870306  24.155235
Portland           9.672464  17.270209  ...  12.945357  15.732797
Sale               8.604589  20.432539  ...  13.591299  18.888856
Sydney            15.031893  23.450178  ...  18.113728  21.900355
SydneyAirport     14.884042  23.414808  ...  18.549930  21.814530
Townsville        20.500579  29.418892  ...  25.739893  27.793510
WaggaWagga         9.916018  23.463535  ...  15.328270  22.176904
Watsonia          10.187399  20.993260  ...  13.909780  19.468864
Williamtown       13.167613  24.439566  ...  18.488397  22.843656
Woomera           13.453633  26.487428  ...  17.921569  25.091984

[26 rows x 16 columns]

In [ ]:
location = df.groupby('Location').mean().reset_index()
location.sort_values('MinTemp', ascending=True)

            Location    MinTemp    MaxTemp  ...  Cloud3pm    Temp9am    Temp3pm
3           Canberra   7.727829  20.363822  ...  4.333952  12.839239  18.917254
18              Sale   8.604589  20.432539  ...  4.934446  13.591299  18.888856
12      MountGambier   8.953996  20.059026  ...  5.354564  13.969168  18.396673
7             Hobart   8.957091  17.783961  ...  4.946364  12.362249  16.096287
17          Portland   9.672464  17.270209  ...  6.044015  12.945357  15.732797
14         Nuriootpa   9.707570  22.026444  ...  4.814243  15.136056  20.601295
22        WaggaWagga   9.916018  23.463535  ...  4.062500  15.328270  22.176904
9   MelbourneAirport   9.958313  20.494537  ...  5.258450  14.123899  18.956606
23          Watsonia  10.187399  20.993260  ...  5.265568  13.909780  19.468864
10           Mildura  10.914225  24.957440  ...  3.898227  15.702120  23.531187
8          Melbourne  11.672445  20.590253  ...  5.294521  14.501370  19.087777
16      PerthAirport  12.681050  25.607793  ...  3.455544  18.870306  24.155235
11             Moree  12.876738  26.937376  ...  3.887611  18.882959  25.640878
15             Perth  13.066215  25.188066  ...  3.436033  18.750975  23.589223
24       Williamtown  13.167613  24.439566  ...  4.154424  18.488397  22.843656
25           Woomera  13.453633  26.487428  ...  2.824683  17.921569  25.091984
4              Cobar  13.828090  26.225281  ...  3.702247  18.523783  24.873034
0       AliceSprings  13.878093  29.724921  ...  3.206028  22.043140  28.457175
5       CoffsHarbour  14.485000  23.766304  ...  4.226812  20.072174  22.193478
20     SydneyAirport  14.884042  23.414808  ...  4.244948  18.549930  21.814530
19            Sydney  15.031893  23.450178  ...  4.150296  18.113728  21.900355
1           Brisbane  16.365628  26.436810  ...  3.827294  21.815137  24.746834
13     NorfolkIsland  16.849432  21.767857  ...  4.701299  19.697768  20.431940
21        Townsville  20.500579  29.418892  ...  3.864407  25.739893  27.793510
2             Cairns  21.129296  29.551596  ...  4.289280  25.790139  27.872013
6             Darwin  23.166492  32.559536  ...  4.264206  27.170967  31.110320

[26 rows x 17 columns]

In [ ]:
pd.crosstab(df.Location, df.MaxTemp)

MaxTemp           4.1   6.3   7.0   7.1   7.2   ...  46.4  46.7  46.8  47.3  48.1
Location                                        ...
AliceSprings         0     0     1     0     0  ...     0     0     0     0     0
Brisbane             0     0     0     0     0  ...     0     0     0     0     0
Cairns               0     0     0     0     0  ...     0     0     0     0     0
Canberra             1     0     0     1     0  ...     0     0     0     0     0
Cobar                0     0     0     0     0  ...     0     0     0     0     0
CoffsHarbour         0     0     0     0     0  ...     0     0     0     0     0
Darwin               0     0     0     0     0  ...     0     0     0     0     0
Hobart               0     0     0     0     1  ...     0     0     0     0     0
Melbourne            0     0     0     0     0  ...     1     0     0     0     0
MelbourneAirport     0     0     0     0     0  ...     0     0     1     0     0
Mildura              0     0     0     0     0  ...     0     1     0     0     0
Moree                0     0     0     0     0  ...     0     0     0     1     0
MountGambier         0     0     0     0     0  ...     0     0     0     0     0
NorfolkIsland        0     0     0     0     0  ...     0     0     0     0     0
Nuriootpa            0     0     0     0     0  ...     0     0     0     0     0
Perth                0     0     0     0     0  ...     0     0     0     0     0
PerthAirport         0     0     0     0     0  ...     0     0     0     0     0
Portland             0     0     0     0     0  ...     0     0     0     0     0
Sale                 0     0     0     0     0  ...     0     0     0     0     0
Sydney               0     0     0     0     0  ...     0     0     0     0     0
SydneyAirport        0     0     0     0     0  ...     1     0     0     0     0
Townsville           0     0     0     0     0  ...     0     0     0     0     0
WaggaWagga           0     1     0     0     0  ...     0     0     0     0     0
Watsonia             0     0     0     0     0  ...     0     1     0     0     0
Williamtown          0     0     0     0     0  ...     0     0     0     0     0
Woomera              0     0     0     0     0  ...     0     0     1     0     1

[26 rows x 395 columns]